[build]
  command = "npm install && chmod +x node_modules/.bin/* && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
