export const days = [
  {
    "day_number": "1",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "The Pattern Introduced",
    "writing_style": "prose",
    "teaching_text": "Most emotional reactions feel instant. A tone lands wrong, a message is ignored, or a comment hits a nerve, and suddenly you are already reacting.\n\n\"I just snapped.\"\n\"It came out of nowhere.\"\n\nBut reactions are rarely as instant as they seem. There is often a fast internal sequence:\nTrigger \u2192 Sensation \u2192 Story \u2192 Response.\nSomething happens.\nYour body reacts.\nYour mind interprets the moment.\nThen behavior follows.\n\nToday is not about stopping the pattern. It is about seeing that the pattern exists.",
    "todays_reminder": "You do not need to fix anything today. Awareness is enough.",
    "todays_note": "You do not need to answer every question. One honest sentence counts.",
    "todays_note_position": "after",
    "reflect_notice": "Think of one recent emotional reaction. What happened?",
    "reflect_look_closer": "What did you feel, think, say, or do first?",
    "reflect_connect": "Did the reaction feel sudden, or were there small signs before it happened?",
    "todays_practice": "Notice one reaction as it begins. Do not stop it or judge it. Simply think: There it is.",
    "micro_win_1": "I showed up today",
    "micro_win_2": "I noticed one reaction",
    "micro_win_3": "I practiced awareness",
    "today_i_feel_1": "More aware",
    "today_i_feel_2": "Curious",
    "today_i_feel_3": "Uncertain but here",
    "today_i_feel_4": "Frustrated",
    "today_i_feel_5": "Resistant",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will begin noticing what patterns repeat.",
    "why_this_matters": "The sequence happens so fast that most people never see it as separate steps. They experience the whole thing as one event \u2014 \"I snapped.\" But it is not one event. It is four. And once you can see the four steps, you can eventually intervene between them. That is where all the work in this workbook leads.",
    "deeper_prompts": "[\"What is your most common reaction \\u2014 do you tend to explode outward, shut down inward, or freeze?\", \"If you could slow down your last reaction to frame-by-frame speed, what would you see happening in the gap between the trigger and your response?\", \"Who in your life sees your reactions most often \\u2014 and what do you think they see that you do not?\"]",
    "try_this": "Tonight, write down one reaction from today in four parts: (1) What happened, (2) What your body did, (3) What story your mind told, (4) What you did or said. Even if the parts blur together, try to separate them.",
    "example": "Your partner says \"we need to talk\" in a flat tone. Your stomach drops (sensation). Your mind says \"they are upset with me again\" (story). You get defensive before they finish the sentence (response). The whole thing takes three seconds \u2014 but each step is distinct."
  },
  {
    "day_number": "2",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "Patterns Repeat",
    "writing_style": "prose",
    "teaching_text": "Your brain learns through repetition.\n\nWhen a situation resembles something painful, stressful, or important from the past, your nervous system may reuse the same response before you have time to think.\n\n\"I always do this.\"\n\"Here we go again.\"\n\nThat familiarity is not a flaw.\nIt is learned efficiency.\nBut old reactions are not always current truth.\n\nToday is about noticing what repeats, not blaming yourself for having a pattern.",
    "todays_reminder": "A pattern is not your identity. It is something you can learn to see.",
    "todays_note": "There is no wrong answer here. Write what is true.",
    "todays_note_position": "after",
    "reflect_notice": "What reaction has shown up more than once in your life?",
    "reflect_look_closer": "In what kinds of situations does this pattern usually appear?",
    "reflect_connect": "What has this pattern cost you in peace, connection, or confidence?",
    "todays_practice": "When a reaction happens today, ask yourself: Have I felt this before?",
    "micro_win_1": "I noticed a repeating pattern",
    "micro_win_2": "I asked the question once",
    "micro_win_3": "I judged myself less",
    "today_i_feel_1": "More aware",
    "today_i_feel_2": "Honest with myself",
    "today_i_feel_3": "Heavy but showing up",
    "today_i_feel_4": "Discouraged",
    "today_i_feel_5": "Numb",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look more closely at your triggers.",
    "why_this_matters": "Patterns repeat because they worked once. At some point, this reaction solved a problem or kept you safe. Your system filed it as the correct response and now runs it automatically whenever a similar situation appears. The pattern is not broken. It is outdated.",
    "deeper_prompts": "[\"Think of a reaction you keep having. Can you remember the first time something like it happened?\", \"What would it mean about you if this pattern stopped \\u2014 what would you have to do or feel differently?\", \"Is there a pattern someone close to you has pointed out that you did not see on your own?\"]",
    "try_this": "Write down three situations from the past month where you reacted in a similar way. Look at them side by side. What is the common thread \u2014 the trigger, the feeling, or the behavior?",
    "example": "You get quiet every time someone raises their voice \u2014 whether it is your partner, your boss, or a stranger. The situations are completely different. The reaction is identical. That is the pattern."
  },
  {
    "day_number": "3",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "Your Triggers",
    "writing_style": "prose",
    "teaching_text": "A trigger is anything that activates your nervous system before your thinking brain catches up.\nA tone.\nA delay.\nA look.\nA word.\nThe feeling of being dismissed, ignored, controlled, or misunderstood.\n\nTriggers are not weakness.\nThey are clues.\nThey show you where your system learned to stay alert.\n\nToday is about naming what sets you off clearly enough that it stops feeling like a mystery.",
    "todays_reminder": "Naming a trigger is not blaming anyone. It is gathering information.",
    "todays_note": "If a question feels too much today, skip it and come back.",
    "todays_note_position": "after",
    "reflect_notice": "Think of a recent strong reaction. What happened in the moments before it started?",
    "reflect_look_closer": "What felt most activating about it \u2014 the words, the tone, or what it reminded you of?",
    "reflect_connect": "Did the situation touch an older feeling or a familiar pain?",
    "todays_practice": "When tension rises today, ask: What specifically set this off?",
    "micro_win_1": "I noticed a trigger",
    "micro_win_2": "I named it clearly",
    "micro_win_3": "I looked beneath the surface",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "Validated",
    "today_i_feel_3": "Stirred up but learning",
    "today_i_feel_4": "Overwhelmed",
    "today_i_feel_5": "Confused",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will begin listening to the signals in your body.",
    "why_this_matters": "Most people know they \"get triggered\" but cannot name the specific trigger. \"They made me angry\" is not a trigger \u2014 it is a result. The trigger is the specific thing that activated the response: a tone, a word, a silence, a feeling of being dismissed. The more precisely you can name it, the earlier you can catch it next time.",
    "deeper_prompts": "[\"Make a short list of your top three triggers \\u2014 the specific situations, tones, or behaviors that most reliably set you off.\", \"Are your triggers mostly about what people do, what they say, or what you interpret about their intention?\", \"Do your triggers change depending on who you are with \\u2014 or are they the same across different relationships?\"]",
    "try_this": "For the rest of today, every time you feel a flash of tension, irritation, or withdrawal, write down what happened in the ten seconds before. Do not analyze it. Just capture the moment.",
    "example": "Your coworker interrupts you mid-sentence in a meeting. The trigger is not \"they interrupted me.\" The trigger is the feeling of being dismissed \u2014 your words did not matter enough for them to wait. That distinction changes everything about how you understand the reaction."
  },
  {
    "day_number": "4",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "Your Body Knows First",
    "writing_style": "prose",
    "teaching_text": "Your body often reacts before your mind explains.\n\nYour jaw tightens.\nYour chest contracts.\nYour breath changes.\nYour stomach drops.\n\nBy the time you realize you are angry, anxious, or hurt, your body may already be in motion.\n\nThese signals are not random. They are early warnings. The earlier you notice them, the more space you have to choose what happens next.\n\nToday is about noticing these signals in your body.",
    "todays_reminder": "Your body is giving you information, not betraying you.",
    "todays_note": "You are allowed to surprise yourself with your answer.",
    "todays_note_position": "after",
    "reflect_notice": "What physical sensation often appears before your reactions?",
    "reflect_look_closer": "Where in your body do stress, anger, or anxiety usually show up?",
    "reflect_connect": "When in your life have you felt calm most easily \u2014 what was different about that time or place?",
    "todays_practice": "Check in with your body three times today and ask: What do I feel right now?",
    "micro_win_1": "I checked in with my body",
    "micro_win_2": "I noticed tension sooner",
    "micro_win_3": "I noticed calm feelings too",
    "today_i_feel_1": "Grounded",
    "today_i_feel_2": "More connected to my body",
    "today_i_feel_3": "Overwhelmed but here",
    "today_i_feel_4": "Disconnected",
    "today_i_feel_5": "Anxious",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at how your environment affects your reactions.",
    "why_this_matters": "Your body runs on a faster system than your conscious mind. By the time you think \"I am angry,\" your jaw has been clenched for minutes. Learning to read your body is like getting an early warning system \u2014 it gives you seconds of lead time that your mind alone cannot provide.",
    "deeper_prompts": "[\"Draw a simple outline of a body. Mark where you feel stress, anger, anxiety, and sadness. Are they in different places?\", \"What does the very beginning of activation feel like for you \\u2014 before it becomes a full emotion?\", \"Do you tend to live more in your head or your body? When did that start?\"]",
    "try_this": "Set three alarms today \u2014 morning, midday, evening. When each one goes off, close your eyes for ten seconds and scan from head to feet. What do you notice? Write one word for each check-in.",
    "example": "You are scrolling your phone before bed and your shoulders are up near your ears. You did not notice. There is no obvious stressor right now \u2014 but your body is still carrying something from the day. That tension is information."
  },
  {
    "day_number": "5",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "The Environment Effect",
    "writing_style": "prose",
    "teaching_text": "You do not react in a vacuum.\n\nSleep loss, hunger, overstimulation, unresolved tension, and stress already in your system all lower your threshold.\n\nA comment that rolls off you on a good day can feel unbearable when you are running on empty.\n\nThis is not weakness.\nIt is context.\n\nToday is about noticing the state you are operating from before judging the reaction.",
    "todays_reminder": "The reaction is rarely just about this moment.",
    "todays_note": "Short answers are complete answers.",
    "todays_note_position": "after",
    "reflect_notice": "What is your emotional baseline today \u2014 how do you feel before anything has happened?",
    "reflect_look_closer": "What is draining you most right now?",
    "reflect_connect": "How does exhaustion, stress, or overstimulation change the way you react?",
    "todays_practice": "Before one hard moment today, ask: What am I carrying already?",
    "micro_win_1": "I checked my baseline",
    "micro_win_2": "I noticed one environmental factor",
    "micro_win_3": "I adjusted with more care",
    "today_i_feel_1": "More aware",
    "today_i_feel_2": "Less judgmental",
    "today_i_feel_3": "Tired but trying",
    "today_i_feel_4": "Depleted",
    "today_i_feel_5": "Irritable",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at how reactions build before they erupt.",
    "why_this_matters": "Context does not excuse the reaction, but it explains the intensity. Understanding that you were already depleted when you snapped does not undo the snap \u2014 but it changes how you prepare for the next one. If you know you are running low, you can lower the demands or raise the support before the moment arrives.",
    "deeper_prompts": "[\"What conditions make your best days \\u2014 sleep, exercise, connection, solitude, routine? What is usually missing on your worst days?\", \"Do you tend to notice your own depletion, or do you push through until something breaks?\", \"How do the people around you affect your baseline \\u2014 who drains it and who restores it?\"]",
    "try_this": "Rate your baseline at the start of tomorrow on a simple 1-5 scale: 1 is empty, 5 is fully resourced. At the end of the day, look at how you reacted and compare it to your morning number. Do this for three days and look for the connection.",
    "example": "You slept four hours, skipped lunch, and had a tense call with your mother. When your partner asks \"what do you want for dinner\" in a perfectly normal tone, you snap. The trigger was not the question. The trigger was everything you were already carrying."
  },
  {
    "day_number": "6",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "How Reactions Build",
    "writing_style": "prose",
    "teaching_text": "Big reactions are often built from smaller moments.\n\nStress from earlier.\nA conversation you swallowed.\nA need you ignored.\nTension carried all day.\nExhaustion no one could see.\n\nThen one final moment happens, and everything comes out at once.\n\nThis does not mean your reaction makes no sense.\nIt means there was more underneath it than it first appeared.\n\nToday is about noticing the buildup before the eruption, so you can understand yourself with more honesty and less shame.",
    "todays_reminder": "The final straw is rarely the whole weight.",
    "todays_note": "Whatever you write here is between you and this page.",
    "todays_note_position": "after",
    "reflect_notice": "What has been building up in you lately?",
    "reflect_look_closer": "What are you carrying that other people may not see?",
    "reflect_connect": "What usually becomes the final straw for you, and why that one?",
    "todays_practice": "At midday and again in the evening, ask: What has accumulated so far today?",
    "micro_win_1": "I noticed what was building",
    "micro_win_2": "I named something I was carrying",
    "micro_win_3": "I understood my intensity better",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "Relieved",
    "today_i_feel_3": "Carrying a lot but aware of it",
    "today_i_feel_4": "Exhausted",
    "today_i_feel_5": "Raw",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will practice observing yourself without judgment. That is a gentler day. You have earned it.",
    "why_this_matters": "The final straw gets all the blame, but it is usually the least important part of the story. Understanding buildup means understanding that your reaction at 6 PM was probably built at 8 AM, noon, and 3 PM. If you can catch the earlier layers, the 6 PM moment may never reach ignition.",
    "deeper_prompts": "[\"Think of your last big reaction. Work backward \\u2014 what happened earlier that day that you absorbed without dealing with?\", \"Do you have a pattern of \\\"swallowing\\\" smaller frustrations? What happens to them?\", \"When you finally erupt, who usually receives the reaction \\u2014 and is it the same person who caused the buildup?\"]",
    "try_this": "At three points today \u2014 late morning, mid-afternoon, and evening \u2014 ask: What has accumulated? Write it down, even if it is just a few words. See if naming the buildup changes how the evening goes.",
    "example": "Your boss gives critical feedback at 10 AM. You smile and nod. A coworker takes credit for your idea at 2 PM. You say nothing. Traffic is bad at 5:30. You grip the wheel. Your kid spills milk at 6:15 and you raise your voice. The milk was not the problem."
  },
  {
    "day_number": "7",
    "week_number": "1",
    "week_theme": "SEE IT",
    "day_title": "Observing Without Judgment",
    "writing_style": "prose",
    "teaching_text": "Many people do not actually observe their reactions.\nThey judge them.\n\nThe moment they notice a reaction, they move into criticism:\n\"I should not have done that.\"\n\"What is wrong with me?\"\n\"I always do this.\"\n\nJudgment ends the observation.\n\nYou stop seeing what actually happened and start attacking yourself instead.\n\nToday is about watching without turning what you see into evidence against you.",
    "todays_reminder": "A calm observer will always see more than an inner critic.",
    "todays_note": "There is no wrong answer here. Write what is true.",
    "todays_note_position": "after",
    "reflect_notice": "What do you usually say to yourself after reacting?",
    "reflect_look_closer": "How do you feel after speaking to yourself that way?",
    "reflect_connect": "What might change if you spoke to yourself differently in those moments?",
    "todays_practice": "Describe one reaction today like a neutral observer. Use only facts. No insults.",
    "micro_win_1": "I noticed my inner voice",
    "micro_win_2": "I paused before piling on",
    "micro_win_3": "I gave myself a little grace",
    "today_i_feel_1": "Gentler with myself",
    "today_i_feel_2": "More aware",
    "today_i_feel_3": "Still showing up",
    "today_i_feel_4": "Self-critical",
    "today_i_feel_5": "Drained",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Next week you will begin looking underneath the reaction.",
    "why_this_matters": "Judgment feels like accountability, but it actually ends the learning. The moment you shift from \"what happened\" to \"what is wrong with me,\" you stop observing and start punishing. Observation without judgment is the foundation of every change that follows in this workbook. Without it, the tools in Weeks 3 and 4 will not land.",
    "deeper_prompts": "[\"Write down exactly what your inner critic says after a reaction \\u2014 the specific words, not a summary.\", \"Whose voice does your inner critic sound like? Is it yours, or did you learn it from someone?\", \"What would change in your life if you could observe a mistake for sixty seconds before judging it?\"]",
    "try_this": "The next time you react in a way you do not like, describe what happened using only facts \u2014 as if you were a security camera with no opinions. No insults, no character judgments, no \"I always\" or \"I never.\" Just what happened.",
    "example": "Instead of: \"I completely lost it again, I am such a mess, I always do this and I will never change\" \u2014 try: \"I raised my voice during a disagreement about schedules. It lasted about thirty seconds. I walked away and felt tense for an hour afterward.\" Same event. One version learns. The other punishes."
  },
  {
    "day_number": "8",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "The Emotion Beneath",
    "writing_style": "prose",
    "teaching_text": "Sometimes the feeling you show first is not the feeling hurting most.\n\nAnger may be protecting hurt.\nDefensiveness may be hiding shame.\nWithdrawal may be covering overwhelm.\nAnxiety may be longing, fear, or loneliness with no words yet.\n\nMany reactions begin as protection.\n\nSomething inside you feels vulnerable, so another emotion steps in first.\nThat does not make you dramatic.\nIt does not make you broken.\n\nIt means there is more going on than it first appears.\nToday is about listening beneath the first reaction, gently and without pressure.",
    "todays_reminder": "The feeling underneath is not the problem. It is information.",
    "todays_note": "You do not need to figure everything out today. Curiosity is enough.",
    "todays_note_position": "before",
    "reflect_notice": "What feeling do you most often react with first? Examples: anger, shutting down, defensiveness, anxiety, irritation",
    "reflect_look_closer": "What feeling might be underneath that reaction? Examples: hurt, fear, sadness, shame, loneliness, overwhelm",
    "reflect_connect": "How might you respond differently if you cared for the deeper feeling instead of only reacting from the surface one?",
    "todays_practice": "When a reaction rises, pause and ask: What am I actually feeling underneath this?",
    "micro_win_1": "I named a surface emotion",
    "micro_win_2": "I looked underneath it",
    "micro_win_3": "I stayed gentle with myself",
    "today_i_feel_1": "Seen",
    "today_i_feel_2": "Tender",
    "today_i_feel_3": "Exposed but safe",
    "today_i_feel_4": "Confused",
    "today_i_feel_5": "Guarded",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will examine the story your mind tells in difficult moments.",
    "why_this_matters": "The surface emotion is like an alarm. It gets your attention, but it does not tell you what is actually wrong. Anger often protects hurt. Defensiveness often hides shame. If you only respond to the alarm and never check what triggered it, the alarm keeps going off. Today starts the work of looking underneath \u2014 which is where the real change happens.",
    "deeper_prompts": "[\"Think of a recent moment when anger showed up. If you peel it back, what was underneath \\u2014 hurt, fear, embarrassment, loneliness, or something else?\", \"Which emotions do you show most easily, and which ones do you almost never let people see?\", \"If the deeper emotion could speak, what would it say \\u2014 what does it need you to hear?\"]",
    "try_this": "The next time you notice a strong surface emotion (anger, defensiveness, withdrawal), pause and ask: What is the softer feeling underneath this? Write it down. You do not need to do anything with it. Just name it.",
    "example": "You get sharp with your partner when they forget something you asked for. The surface emotion is irritation. Underneath: you feel unseen. You feel like your needs do not register. The sharpness is not about the forgotten task \u2014 it is about the feeling of not mattering enough to be remembered."
  },
  {
    "day_number": "9",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "The Story You Tell",
    "writing_style": "prose",
    "teaching_text": "Between what happens and how you feel, your mind creates a story \u2014 fast, automatic, and rarely questioned.\n\nThey do not respect me.\nI am being ignored.\nI am not enough.\nThis always happens to me.\n\nThese stories feel true because they are familiar.\n\nBut they are often fast interpretations, not full reality.\n\nToday is about noticing the story without automatically believing it.",
    "todays_reminder": "The first story is not always the full truth.",
    "todays_note": "If a question feels too much today, skip it and come back.",
    "todays_note_position": "after",
    "reflect_notice": "Think of a recent reaction. What story did your mind tell you?",
    "reflect_look_closer": "What evidence supports that story, and what evidence complicates it?",
    "reflect_connect": "Where might this story have started \u2014 how old does it feel?",
    "todays_practice": "When a reaction builds, ask: What story am I telling right now?",
    "micro_win_1": "I identified a story",
    "micro_win_2": "I questioned it gently",
    "micro_win_3": "I made room for more truth",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "Less stuck",
    "today_i_feel_3": "Unsettled but thinking",
    "today_i_feel_4": "Defensive",
    "today_i_feel_5": "Skeptical",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at the fear underneath the story.",
    "why_this_matters": "The mind is a meaning-making machine. It takes a small piece of data \u2014 a tone, a pause, a facial expression \u2014 and builds a full narrative in seconds. The problem is not that the mind makes stories. The problem is that it presents them as facts. Learning to see the story as a story, not a verdict, is one of the most powerful shifts in this entire workbook.",
    "deeper_prompts": "[\"What is the story your mind tells most often in conflict \\u2014 is it about being abandoned, being not enough, being controlled, or being disrespected?\", \"When the story is running, how certain does it feel? Rate it on a 1-10. Now ask: what evidence would change the number?\", \"Have you ever been completely sure about a story \\u2014 and later discovered it was wrong? What happened?\"]",
    "try_this": "Write down one story your mind told you this week. Then write two alternative explanations for the same event. You do not have to believe them \u2014 just notice that more than one version is possible.",
    "example": "Your friend does not text back for a day. Your mind says: \"They are pulling away. I said something wrong. They do not care.\" Alternative: they are busy, their phone died, or they read it and forgot to reply. All are equally possible. The story picked the most painful one and called it truth."
  },
  {
    "day_number": "10",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "The Fear Underneath",
    "writing_style": "prose",
    "teaching_text": "Many intense reactions have fear at their core.\n\nNot always fear of danger, but fear of rejection, abandonment, humiliation, inadequacy, or losing control.\n\n\"What if they leave?\"\n\"What if I am not enough?\"\n\nWhen fear stays unnamed, it often drives behavior from the background.\n\nWhen you name it clearly, it usually loses some of its grip.\n\nToday is about bringing fear into language with care.",
    "todays_reminder": "Name the fear and it begins to loosen its hold.",
    "todays_note": "You are allowed to surprise yourself with your answer. And if naming the fear feels like too much today \u2014 writing \"I am not sure yet\" is a complete answer.",
    "todays_note_position": "after",
    "reflect_notice": "What fear might live underneath your most common reaction?",
    "reflect_look_closer": "What are you afraid this moment means or confirms about you?",
    "reflect_connect": "When do you first remember feeling this fear?",
    "todays_practice": "When a reaction surfaces, quietly say: I am afraid this means ___.",
    "micro_win_1": "I named a fear",
    "micro_win_2": "I did not minimize it",
    "micro_win_3": "I treated myself with care",
    "today_i_feel_1": "Brave",
    "today_i_feel_2": "Tender",
    "today_i_feel_3": "Shaken but honest",
    "today_i_feel_4": "Overwhelmed",
    "today_i_feel_5": "Numb",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at where your patterns first began.",
    "why_this_matters": "Fear is the engine underneath most emotional patterns. Not fear of physical danger \u2014 fear of what certain moments mean about you, about your relationships, about your future. When the fear stays unnamed, it drives the bus from the back seat. When you name it, you do not make it disappear \u2014 but you take it out of the driver's seat.",
    "deeper_prompts": "[\"Complete this sentence five times with different answers: \\\"What I am really afraid of is ___\\\"\", \"Which of your fears is the oldest \\u2014 the one that has been with you longest? Where does it come from?\", \"What would your life look like if this fear lost its grip \\u2014 not disappeared, but loosened? What would you do differently?\"]",
    "try_this": "Write your deepest fear about yourself in one sentence. Read it out loud. Notice what happens in your body. Then write: \"That is a fear, not a fact.\" This is not about believing it yet \u2014 it is about practicing the separation.",
    "example": "You avoid asking for what you need because you are afraid of being \"too much.\" The fear is not about the specific request \u2014 it is about the belief that your needs will push people away. That fear may have started with someone specific. It is running as if it applies to everyone."
  },
  {
    "day_number": "11",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "Where It Began",
    "writing_style": "prose",
    "teaching_text": "Your emotional patterns did not begin out of nowhere. Many were shaped in childhood, early relationships, school, or formative moments that taught you what was safe and what was not. Looking back is not about blame. It is about understanding. You are not returning to the past to live there. You are looking back so you can stop confusing old protection with present truth.",
    "todays_reminder": "Go gently today. You only need to notice what feels useful.",
    "todays_note": "Whatever you write here is between you and this page.",
    "todays_note_position": "after",
    "reflect_notice": "When do you first remember developing this emotional pattern?",
    "reflect_look_closer": "What did that time teach you about feelings, needs, or safety?",
    "reflect_connect": "How might that old lesson still be running in your life now?",
    "todays_practice": "Offer one kind sentence to the younger version of you who learned this pattern. If that feels like too much, try this: \"It makes sense that you learned to protect yourself this way.\"",
    "micro_win_1": "I looked back gently",
    "micro_win_2": "I saw protection instead of failure",
    "micro_win_3": "I practiced compassion",
    "today_i_feel_1": "Compassionate",
    "today_i_feel_2": "Reflective",
    "today_i_feel_3": "Sad but not alone",
    "today_i_feel_4": "Angry",
    "today_i_feel_5": "Heavy",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at the need beneath the reaction.",
    "why_this_matters": "Your emotional patterns were survival strategies. They were not mistakes \u2014 they were reasonable responses to the environment you were in. A child who learns to stay quiet because loud feelings were punished is not broken \u2014 they adapted. The problem is that the adaptation keeps running long after the original environment has changed.",
    "deeper_prompts": "[\"What was the emotional climate of your childhood \\u2014 was it safe to have big feelings, or did you learn to manage them alone?\", \"What rules about emotions did you absorb without anyone saying them out loud? (Examples: anger is dangerous, crying is weak, needs are burdens)\", \"If you could tell your younger self one thing about the pattern they were developing, what would it be?\"]",
    "try_this": "Write a short letter to the younger version of you \u2014 the one who first learned this pattern. Tell them what you understand now that they could not have known then. You do not need to share it. It is just for you.",
    "example": "You learned to handle everything yourself because asking for help meant being seen as weak. That worked when you were twelve and the adults around you could not be relied on. It does not work at thirty-five when your partner genuinely wants to share the load."
  },
  {
    "day_number": "12",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "What You Actually Need",
    "writing_style": "prose",
    "teaching_text": "Beneath many reactions is an unmet need: to feel safe, seen, respected, included, understood, supported, or given space. Most people were never taught to name needs clearly, so they express the reaction and hope someone else understands the message. Today is about naming the need directly, even if only to yourself.",
    "todays_reminder": "A need is not too much. It is information.",
    "todays_note": "Short answers are complete answers.",
    "todays_note_position": "after",
    "reflect_notice": "Think of a recent reaction. What did you actually need in that moment?",
    "reflect_look_closer": "What needs show up again and again in your reactions?",
    "reflect_connect": "What makes it hard to express those needs directly?",
    "todays_practice": "Before reacting today, ask: What do I need right now?",
    "micro_win_1": "I named one need",
    "micro_win_2": "I made it specific",
    "micro_win_3": "I noticed how it changed my response",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "More honest",
    "today_i_feel_3": "Vulnerable but grounded",
    "today_i_feel_4": "Ashamed",
    "today_i_feel_5": "Frustrated",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at the cost of suppressing emotions.",
    "why_this_matters": "Unmet needs do not go away because you stop naming them. They show up as reactions \u2014 as anger, as withdrawal, as people-pleasing, as control. Every time you react instead of naming the need, you make it harder for the people around you to actually meet it. Naming the need is not selfish. It is the clearest communication you can offer.",
    "deeper_prompts": "[\"What need shows up most in your closest relationship \\u2014 to be heard, to be respected, to be prioritized, to be safe, or something else?\", \"When you do express a need, how do you usually do it \\u2014 directly, indirectly, through frustration, or not at all?\", \"What would it feel like to say \\\"I need ___\\\" without apologizing for it?\"]",
    "try_this": "Think of your last reaction. Complete this sentence: \"What I actually needed in that moment was ___\". Then ask: did I communicate that need, or did I just react and hope they figured it out?",
    "example": "You get angry when your partner makes plans without checking with you. The reaction is anger. The need underneath is to be included \u2014 to feel like your time and preferences matter. If you name the need, they can respond to it. If you only show the anger, they respond to that instead."
  },
  {
    "day_number": "13",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "The Cost of Suppression",
    "writing_style": "prose",
    "teaching_text": "Suppressing emotions does not erase them. It usually postpones them. Feelings pushed down often leak out as irritability, tension, numbness, withdrawal, or sudden eruptions in moments that seem unrelated. \"I am fine\" is sometimes the most expensive sentence you say. Suppression can feel like control in the short term. Over time, it often costs more than it protects. Today is about noticing what you push away and where it goes.",
    "todays_reminder": "Acknowledging an emotion is not the same as being controlled by it.",
    "todays_note": "There is no wrong answer here. Write what is true.",
    "todays_note_position": "after",
    "reflect_notice": "What emotions do you most often suppress?",
    "reflect_look_closer": "How do suppressed feelings tend to show up later?",
    "reflect_connect": "What has suppression cost you in your body, relationships, or self-trust?",
    "todays_practice": "When you notice yourself pushing a feeling away, name it privately instead.",
    "micro_win_1": "I noticed a suppression habit",
    "micro_win_2": "I named one feeling instead of pushing it away",
    "micro_win_3": "I stayed present briefly",
    "today_i_feel_1": "More honest",
    "today_i_feel_2": "Present",
    "today_i_feel_3": "Uncomfortable but awake",
    "today_i_feel_4": "Overwhelmed",
    "today_i_feel_5": "Resistant",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will practice holding emotional complexity.",
    "why_this_matters": "Suppression feels like control. It looks like maturity. But it has a cost that compounds over time. The feelings you push down do not dissolve \u2014 they leak. They show up as irritability with people who did not cause the original feeling, as tension in your body, as numbness that makes it hard to feel anything at all.",
    "deeper_prompts": "[\"What emotion do you suppress most \\u2014 and where did you learn that it was not safe to express?\", \"When suppressed feelings finally come out, how do they usually show up \\u2014 as a sudden outburst, as physical symptoms, as emotional numbness, or as something else?\", \"Is there a feeling you have been carrying for a long time that you have never said out loud to anyone?\"]",
    "try_this": "Choose one feeling you have been pushing down this week. Set a timer for five minutes and write about it \u2014 what it is, where it lives in your body, and what it would say if it could speak. You are not fixing it. You are giving it room.",
    "example": "You are fine all week. Cheerful, productive, holding it together. Then on Sunday evening you feel a wave of sadness you cannot explain. It is not random. It is everything you pushed aside during the week finally finding a gap to surface."
  },
  {
    "day_number": "14",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "day_title": "Holding Complexity",
    "writing_style": "prose",
    "teaching_text": "Emotional maturity often means allowing more than one truth to exist at the same time. You can love someone and feel angry with them. You can feel grief and relief together. You can want connection and need space. When the mind tries to simplify complex feelings too quickly, it can edit out important truth. Today is about letting both sides exist without forcing one to win.",
    "todays_reminder": "Complexity is not confusion. It is accuracy.",
    "todays_note": "If a question feels too much today, skip it and come back.",
    "todays_note_position": "after",
    "reflect_notice": "What situation or relationship in your life carries mixed feelings?",
    "reflect_look_closer": "Which feeling do you usually allow, and which one do you push aside?",
    "reflect_connect": "What might change if both feelings were allowed to be true?",
    "todays_practice": "Write or say: It is true that I feel ___. It is also true that I feel ___. For example: It is true that I feel relieved. It is also true that I feel guilty.",
    "micro_win_1": "I named mixed feelings",
    "micro_win_2": "I let both sides exist",
    "micro_win_3": "I did not force a simple answer",
    "today_i_feel_1": "More honest",
    "today_i_feel_2": "Grounded",
    "today_i_feel_3": "Conflicted and that is allowed",
    "today_i_feel_4": "Confused",
    "today_i_feel_5": "Torn",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Next week you will begin building tools to shift the pattern.",
    "why_this_matters": "Emotional complexity is a sign of maturity, not confusion. The ability to hold two conflicting truths \u2014 I love this person and I am angry with them, I want to leave and I am afraid to go \u2014 is not weakness. It is accuracy. Most real feelings are not simple. Forcing them to be simple means editing out the truth.",
    "deeper_prompts": "[\"What relationship in your life holds the most mixed feelings \\u2014 and which feeling do you usually let win?\", \"What would happen if you said both feelings out loud to someone you trust \\u2014 the comfortable one and the uncomfortable one?\", \"Where in your life have you been forcing a simple answer onto a complex situation?\"]",
    "try_this": "Complete this sentence three times about the same situation: \"It is true that I feel ___. It is also true that I feel ___.\" Do not pick a winner. Let both sit.",
    "example": "You are relieved your parent moved to assisted living. You also feel crushing guilt about it. Both are true. If you only allow the relief, the guilt leaks out as overcompensation. If you only allow the guilt, you burn out. The honest answer holds both."
  },
  {
    "day_number": "15",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "The Three-Second Window",
    "writing_style": "prose",
    "teaching_text": "Between what happens and how you respond, there is a gap, even if it feels very small. That gap can be widened through practice. Not through perfection or force, but through repetition. Every time you notice the urge to react and pause for even a few seconds, you make choice more available. Today you begin with the simplest interruption: three seconds.",
    "todays_reminder": "Three seconds can change everything that follows.",
    "todays_note": "You are allowed to surprise yourself with your answer.",
    "todays_note_position": "after",
    "reflect_notice": "Think of a reaction you wish had gone differently. Where could a pause have helped?",
    "reflect_look_closer": "What makes pausing hardest for you in charged moments?",
    "reflect_connect": "Have you ever caught yourself and chosen differently? What made that possible?",
    "todays_practice": "Count to three before responding in one charged moment today.",
    "micro_win_1": "I paused once",
    "micro_win_2": "I slowed the moment down",
    "micro_win_3": "I created space for choice",
    "today_i_feel_1": "Capable",
    "today_i_feel_2": "More steady",
    "today_i_feel_3": "Frustrated but practicing",
    "today_i_feel_4": "Impatient",
    "today_i_feel_5": "Doubtful",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will add a breathing reset to the pause.",
    "why_this_matters": "The three-second pause is the smallest unit of change in this entire workbook. It does not require understanding your childhood, naming your fears, or rewriting your story. It only requires noticing the urge to react and waiting three seconds before acting on it. That gap \u2014 tiny as it is \u2014 is where every other tool becomes available.",
    "deeper_prompts": "[\"Think of a recent reaction that went badly. Where exactly in the sequence would three seconds have changed the outcome?\", \"What does your body feel like in the gap between the urge and the action? Is it tension, pressure, speed, or something else?\", \"What usually pulls you out of the pause \\u2014 the intensity of the feeling, the speed of the other person, or your own habit?\"]",
    "try_this": "Practice the pause in low-stakes moments today \u2014 before replying to a text, before reacting to a minor annoyance, before speaking in a conversation. Build the muscle where the cost of failure is low.",
    "example": "Your teenager rolls their eyes. The urge to lecture arrives instantly. Three seconds. In those three seconds, you can feel the urge without acting on it. You can choose: lecture, or ask a question, or say nothing. The pause did not remove the reaction \u2014 it gave you options."
  },
  {
    "day_number": "16",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "The Physiological Reset",
    "writing_style": "prose",
    "teaching_text": "When your nervous system is activated, reasoning gets harder. You cannot always think your way calm, but you can often breathe your way toward more steadiness. A slower exhale than inhale helps signal safety to the body. This is not about forcing calm. It is about giving your system a physical cue that the moment can slow down.",
    "todays_reminder": "A six-count exhale is faster than any apology you will have to make later.",
    "todays_note": "Whatever you write here is between you and this page.",
    "todays_note_position": "after",
    "reflect_notice": "How do you usually try to calm yourself when activated?",
    "reflect_look_closer": "What has helped you calm down in the past, even accidentally?",
    "reflect_connect": "Where in your life has slowing down \u2014 even briefly \u2014 changed how something went?",
    "todays_practice": "Practice this three times today: inhale for 4, pause for 1, exhale for 6.",
    "micro_win_1": "I practiced the reset breath",
    "micro_win_2": "I noticed a body shift",
    "micro_win_3": "I used breath as a tool",
    "today_i_feel_1": "Calmer",
    "today_i_feel_2": "Grounded",
    "today_i_feel_3": "Skeptical but trying",
    "today_i_feel_4": "Restless",
    "today_i_feel_5": "Disconnected",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will practice naming what is real.",
    "why_this_matters": "When your body is activated, your thinking brain goes partially offline. Reasoning, perspective, empathy \u2014 these require a calm system to operate. You cannot think your way out of an activated body. But you can breathe your way back to a state where thinking works again. The exhale is the fastest legal drug for calming your system.",
    "deeper_prompts": "[\"What do you usually do when you try to calm down \\u2014 and does it actually work, or does it just move the tension somewhere else?\", \"Have you ever felt the moment when your body shifts from activated to calmer? What does that transition feel like?\", \"Where in your life would a ten-second breathing reset make the biggest difference?\"]",
    "try_this": "Practice the 4-1-6 breath five times right now. Inhale for 4, pause for 1, exhale for 6. After five rounds, notice what shifted \u2014 even if the shift is small. The point is not to feel calm. The point is to feel the shift.",
    "example": "You are about to send an angry email. Your chest is tight, your hands are fast on the keyboard. You pause. Inhale for 4. Pause. Exhale for 6. Do it three times. Then reread the email. The email changes \u2014 not because you changed your mind, but because your body calmed down enough for your mind to think clearly."
  },
  {
    "day_number": "17",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "Naming What Is Real",
    "writing_style": "prose",
    "teaching_text": "Putting feelings into words can lower their intensity. Naming moves the brain from raw reaction toward awareness. The goal is not to deny what you feel. It is to become precise about it. \"I notice frustration\" is a different experience than becoming the frustration. Today you use simple, accurate language to create distance without disconnecting from yourself.",
    "todays_reminder": "You are not the emotion. You are the one noticing it.",
    "todays_note": "Short answers are complete answers.",
    "todays_note_position": "after",
    "reflect_notice": "What emotion is most present for you today?",
    "reflect_look_closer": "What more precise word fits better than angry, sad, or anxious?",
    "reflect_connect": "Which feelings are hardest for you to name, and why?",
    "todays_practice": "When a difficult feeling appears, say internally: I notice ___.",
    "micro_win_1": "I named one feeling precisely",
    "micro_win_2": "I used language to create space",
    "micro_win_3": "I noticed the shift after naming",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "More regulated",
    "today_i_feel_3": "Numb but working on it",
    "today_i_feel_4": "Foggy",
    "today_i_feel_5": "Frustrated",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will combine your tools and choose your response.",
    "why_this_matters": "Naming an emotion does something measurable. It moves brain activity from the fast-reacting parts toward the parts that plan and regulate. \"I notice frustration\" is a genuinely different experience than being frustration. The naming creates distance \u2014 not disconnection, but enough space to choose what happens next.",
    "deeper_prompts": "[\"How many emotions can you name beyond happy, sad, angry, and anxious? Try to list ten. If you struggle, that is information.\", \"What emotion do you feel most often that you have the hardest time naming precisely?\", \"Does naming an emotion make it feel bigger, smaller, or just different? Notice without judging the answer.\"]",
    "try_this": "For the rest of today, every time you feel something, try to name it with a word more precise than \"bad\" or \"fine.\" Frustrated. Overlooked. Tender. Relieved. Worried. Noticed. The more precise the word, the more useful it becomes.",
    "example": "You feel \"bad\" after a meeting. But \"bad\" could be twenty things. When you slow down: you feel embarrassed because you stumbled over your words, and underneath that, you feel afraid that people think you are not competent. \"Bad\" does not give you anything to work with. \"Embarrassed and afraid of being judged\" does."
  },
  {
    "day_number": "18",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "Choosing Your Response",
    "writing_style": "prose",
    "teaching_text": "You have been building toward this: pause, breathe, name, choose. Once you have even a little space, a different question becomes possible. Not what do I automatically do here, but what response would serve this moment and the person I want to be? Today is not about a perfect response. It is about a conscious one.",
    "todays_reminder": "One conscious choice is real progress.",
    "todays_note": "There is no wrong answer here. Write what is true.",
    "todays_note_position": "after",
    "reflect_notice": "Think of a charged moment. What response would you choose now?",
    "reflect_look_closer": "When you are grounded, how do you want to handle conflict or stress?",
    "reflect_connect": "What usually pulls you away from that grounded version of yourself?",
    "todays_practice": "In one charged moment, pause, breathe, name the feeling, and ask: What response do I want to make here?",
    "micro_win_1": "I used one tool consciously",
    "micro_win_2": "I asked before reacting",
    "micro_win_3": "I chose with more intention",
    "today_i_feel_1": "Empowered",
    "today_i_feel_2": "More steady",
    "today_i_feel_3": "Imperfect but choosing",
    "today_i_feel_4": "Overwhelmed",
    "today_i_feel_5": "Self-critical",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will practice rewriting the story.",
    "why_this_matters": "Pause, breathe, name, choose \u2014 these are the four steps working together. Separately, each one helps. Together, they form a complete system for responding instead of reacting. Today is the day you put them together in a real moment. It will not be perfect. It does not need to be. One conscious response in a day that otherwise runs on autopilot is a genuine shift.",
    "deeper_prompts": "[\"Which step in the sequence (pause, breathe, name, choose) comes most naturally to you \\u2014 and which one breaks down first?\", \"When you imagine responding instead of reacting in your hardest relationship, what does it look like specifically?\", \"What has an automatic reaction cost you recently that a chosen response would have handled differently?\"]",
    "try_this": "Choose one predictable charged moment today \u2014 a meeting, a conversation, a transition. Before it happens, rehearse the sequence in your mind: pause, breathe, name what I feel, choose my response. Then try it live.",
    "example": "Your coworker gives you critical feedback in front of the team. Old pattern: shut down, smile, seethe internally for three hours. New sequence: pause (feel the heat rise), breathe (one exhale), name (I feel exposed and defensive), choose (ask a clarifying question instead of shutting down). It takes ten seconds."
  },
  {
    "day_number": "19",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "Rewriting the Story",
    "writing_style": "prose",
    "teaching_text": "Old stories feel true because they are familiar. People leave. I am not enough. I cannot trust anyone. These stories may have started in real pain, but they are often incomplete. Rewriting the story is not pretending everything is fine. It is asking whether a version exists that includes both the pain and the evidence that something else may also be true.",
    "todays_reminder": "Accuracy is more grounding than catastrophe.",
    "todays_note": "You are allowed to surprise yourself with your answer.",
    "todays_note_position": "after",
    "reflect_notice": "What old story gets activated during your reactions?",
    "reflect_look_closer": "What evidence does not fully fit that story?",
    "reflect_connect": "What would a more complete version of the story sound like?",
    "todays_practice": "When the old story appears, add: And it is also true that ___.",
    "micro_win_1": "I noticed an old story",
    "micro_win_2": "I added another truth",
    "micro_win_3": "I practiced accuracy over catastrophe",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "Less trapped",
    "today_i_feel_3": "Struggling but thinking differently",
    "today_i_feel_4": "Defensive",
    "today_i_feel_5": "Skeptical",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will practice setting limits.",
    "why_this_matters": "Old stories persist because they were built on real pain. \"People leave\" may have started because someone important actually did leave. The story is not a lie \u2014 it is an incomplete truth. Rewriting the story is not about denying the pain. It is about adding what the story leaves out: the people who stayed, the times you were enough, the evidence that contradicts the verdict the story keeps handing down.",
    "deeper_prompts": "[\"What is the oldest story you tell about yourself \\u2014 the one that feels most like a permanent truth?\", \"If you read that story as if it were about someone else, what would you say to them?\", \"What evidence from the last year directly contradicts your oldest story?\"]",
    "try_this": "Write your most common looping story in one sentence. Then write \"And it is also true that ___\" three times, each with a different piece of evidence the story ignores. Read all four sentences together.",
    "example": "Story: \"I am not enough.\" Evidence the story ignores: you were promoted last year, your friend called you first when they were in crisis, your partner chose you again this morning. The story grabs the rejection and ignores the evidence. A complete story holds both."
  },
  {
    "day_number": "20",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "Setting Limits",
    "writing_style": "prose",
    "teaching_text": "Many emotional reactions come from limits that were never stated. When you tolerate what you cannot sustain, resentment builds quietly and erupts loudly. A clear limit is not punishment or rejection. It is honest communication about what you need in order to remain present, respectful, and intact. Today is about practicing one small limit before frustration has to speak for you.",
    "todays_reminder": "A limit stated simply can protect both your peace and your relationships.",
    "todays_note": "Whatever you write here is between you and this page.",
    "todays_note_position": "after",
    "reflect_notice": "Where in your life do you feel closest to your limit?",
    "reflect_look_closer": "What limit have you been avoiding or softening?",
    "reflect_connect": "What are you afraid will happen if you say it clearly?",
    "todays_practice": "State one small limit today simply and respectfully.",
    "micro_win_1": "I noticed a limit I had been avoiding",
    "micro_win_2": "I practiced clear language",
    "micro_win_3": "I respected my capacity",
    "today_i_feel_1": "Clearer",
    "today_i_feel_2": "Stronger",
    "today_i_feel_3": "Afraid but doing it anyway",
    "today_i_feel_4": "Guilty",
    "today_i_feel_5": "Exposed",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will learn what to do when the tools fail.",
    "why_this_matters": "Many people confuse limits with ultimatums. A limit is not a threat. It is information about what you need in order to stay present, respectful, and intact. When you do not state limits, resentment builds \u2014 and resentment is one of the most common drivers of emotional reactivity. A clear limit prevents the buildup that leads to the explosion.",
    "deeper_prompts": "[\"Where in your life are you tolerating something that is slowly building resentment?\", \"What limit would you set if you knew the other person would not get angry or hurt?\", \"What did you learn about limits growing up \\u2014 were they respected, punished, or ignored?\"]",
    "try_this": "Write down one limit you need to set. Then write the simplest version of it \u2014 one sentence, no justification, no apology. Practice saying it out loud. Notice what happens in your body when you say it.",
    "example": "Instead of: \"I feel like maybe sometimes it would be helpful if possibly you could let me know before making big plans because it kind of bothers me when I do not find out until later\" \u2014 try: \"I need to be included in plans that affect my schedule.\" Same limit. One lands."
  },
  {
    "day_number": "21",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "day_title": "When the Tools Fail",
    "writing_style": "prose",
    "teaching_text": "There will be moments when the pause does not form fast enough, the breath is impossible to find, and the name will not come. Not because the tools do not work, but because the activation is too fast or the pattern too deeply grooved. Most people use these moments as evidence that they have failed. They are not failure. They are the moments the work was always preparing you for. What you do after you have already reacted is its own skill.",
    "todays_reminder": "Recovery after a reaction is not a consolation prize. It is the practice itself.",
    "todays_note": "If a question feels too much today, skip it and come back.",
    "todays_note_position": "after",
    "reflect_notice": "Think of a recent moment when a reaction ran before any tool could reach it. What happened?",
    "reflect_look_closer": "Which part of the sequence broke down first \u2014 the pause, the breath, the name, or the choice?",
    "reflect_connect": "What would the most honest and useful recovery have looked like after the fact?",
    "todays_practice": "If you have reacted this week in a way you regret, complete the loop today: name it, acknowledge the impact, identify what you would do differently, and let it go.",
    "micro_win_1": "I identified where the sequence broke down",
    "micro_win_2": "I treated the slip as data, not failure",
    "micro_win_3": "I made or planned a repair",
    "today_i_feel_1": "Honest",
    "today_i_feel_2": "More resilient",
    "today_i_feel_3": "Discouraged but not giving up",
    "today_i_feel_4": "Defeated",
    "today_i_feel_5": "Ashamed",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Next week you take everything you have learned into the places that matter most \u2014 your relationships, your work, and your own mind.",
    "why_this_matters": "This day matters because it removes the excuse to quit. If every slip is a failure, eventually the slips pile up and you abandon the work. But if recovery is a skill \u2014 one you can practice and get better at \u2014 then slipping becomes part of the process instead of evidence against it. The fastest growth often happens in the recovery, not in the perfect moments.",
    "deeper_prompts": "[\"How do you usually treat yourself after a slip \\u2014 with curiosity, with punishment, or with avoidance?\", \"What would a good recovery look like for you \\u2014 what specific steps would it include?\", \"Is there a slip from this week that you are still carrying shame about? Can you complete the loop on it now?\"]",
    "try_this": "Write a recovery script \u2014 three sentences you can say to yourself after a reaction runs before any tool could stop it. Make it honest, not cheerful. Something you would actually believe in the moment. Keep it where you can find it.",
    "example": "Recovery script: \"That reaction ran faster than I could catch it. That does not erase what I have been building. The next step is: name what happened, acknowledge the impact, and move forward with what I know now.\""
  },
  {
    "day_number": "22",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "In Your Closest Relationship",
    "writing_style": "prose",
    "teaching_text": "The most important test of everything you have built happens in your closest relationships. The people who know you best also know where your patterns live. They trigger them accidentally and sometimes intentionally. Because you care about those relationships, the stakes feel highest there. Today you bring one conscious tool into the room with the person who matters most.",
    "todays_reminder": "The relationship is not the obstacle to your growth. It is the place where growth becomes real.",
    "todays_note": "Short answers are complete answers.",
    "todays_note_position": "after",
    "reflect_notice": "Which relationship in your life most reliably activates your old pattern?",
    "reflect_look_closer": "What do you tend to do in that relationship when things get hard \u2014 pull away, push harder, lose it, or go quiet?",
    "reflect_connect": "What response do you most want to be able to make consistently in that relationship?",
    "todays_practice": "Choose one important relationship today and bring one conscious tool to it: a pause, a need expressed directly, or a limit stated simply.",
    "micro_win_1": "I brought one tool to a key relationship",
    "micro_win_2": "I noticed my old role and named it",
    "micro_win_3": "I separated what I can control from what I cannot",
    "today_i_feel_1": "Brave",
    "today_i_feel_2": "More present",
    "today_i_feel_3": "Scared but showing up",
    "today_i_feel_4": "Disappointed",
    "today_i_feel_5": "Drained",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will bring these tools into professional settings.",
    "why_this_matters": "Close relationships are not harder because the tools do not work there. They are harder because the stakes are higher and the patterns are deeper. The people who love you most have the most access to your oldest patterns. Bringing even one conscious tool into that space changes the dynamic \u2014 not just for you, but for the relationship itself.",
    "deeper_prompts": "[\"What role do you play in your most difficult relationship \\u2014 the fixer, the peacekeeper, the withdrawer, or the fighter? Where did you learn that role?\", \"What would it look like to respond to this person from your grounded self instead of your patterned self?\", \"What is one thing you have never said to this person that you need them to hear?\"]",
    "try_this": "Before your next interaction with the person you overthink about most, set one intention: I will use one tool. Just one. It can be a pause, a breath, a named feeling, or a stated need. Decide which one before the interaction starts.",
    "example": "Your partner criticizes how you loaded the dishwasher. Old pattern: snap back or shut down. New approach: pause. Feel the flash of \"I am being controlled.\" Name it internally: that is the old story. Choose: \"I hear you. I did it differently. Is it important to you that it is done a specific way?\" The dynamic shifts."
  },
  {
    "day_number": "23",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "Under Professional Pressure",
    "writing_style": "prose",
    "teaching_text": "Work is where many emotional patterns run at their most chronic and least examined.\n\nCriticism from a manager can activate the same fear of inadequacy you felt at twelve.\n\nBeing overlooked triggers the same ache as being left out when you were young.\n\nThe professional stakes feel different, but the emotional wiring underneath is identical.\n\nEverything you have built applies here just as powerfully.",
    "todays_reminder": "Your professional reactions run on personal wiring. Seeing both changes everything.",
    "todays_note": "You do not need to answer every question. One honest sentence counts.",
    "todays_note_position": "after",
    "reflect_notice": "How does your most common emotional pattern show up at work?",
    "reflect_look_closer": "What makes managing your reactions at work feel different from at home?",
    "reflect_connect": "What has your emotional reactivity cost you professionally?",
    "todays_practice": "Before your most challenging professional interaction today, name your pattern, your need, and your response goal in advance.",
    "micro_win_1": "I named my pattern before a professional situation",
    "micro_win_2": "I used at least one tool during a work interaction",
    "micro_win_3": "I separated the work situation from the personal pattern",
    "today_i_feel_1": "More intentional",
    "today_i_feel_2": "Clear-headed",
    "today_i_feel_3": "Exhausted but aware",
    "today_i_feel_4": "Frustrated",
    "today_i_feel_5": "Resentful",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will turn the same tools inward, toward yourself.",
    "why_this_matters": "Professional settings add a layer of complexity because the emotional patterns are running but the rules of expression are different. You cannot slam a door or cry at your desk without consequences. So the emotions go underground \u2014 and underground emotions drive more of your professional behavior than you realize. Seeing the personal wiring underneath the professional surface changes how you navigate every workday.",
    "deeper_prompts": "[\"What professional situation activates you most \\u2014 criticism, being overlooked, conflict with authority, or something else? Why that one?\", \"How is your work persona different from your home self \\u2014 and what does that gap cost you?\", \"If your emotional reactivity at work was completely resolved, what would you do differently \\u2014 in meetings, in conversations, in your career decisions?\"]",
    "try_this": "Before your most charged professional interaction today, write down: my pattern is ___, my need is ___, and the response I want to choose is ___. Then carry the note with you.",
    "example": "Your manager gives vague feedback. Old pattern: spiral for hours trying to decode what they really meant, assume the worst, overwork to compensate. With tools: name the story (\"I am afraid this means I am underperforming\"), test it (\"what did they actually say vs. what I added\"), choose (\"I will ask a clarifying question instead of guessing\")."
  },
  {
    "day_number": "24",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "When You Are Alone",
    "writing_style": "fragment",
    "teaching_text": "Some of your hardest emotional moments happen where no one can see them.\n\nThe spiral after a mistake.\n\nThe anxiety at night.\n\nThe private cruelty you would never use on anyone else.\n\nHow you treat yourself in private shapes everything else.\n\nToday is about changing the voice that follows you home.",
    "todays_reminder": "The voice you use on yourself is the one you live inside. It is worth changing.",
    "todays_note": "There is no wrong answer here. Write what is true.",
    "todays_note_position": "before",
    "reflect_notice": "What does your inner critic sound like, and when is it loudest?",
    "reflect_look_closer": "Do you hold yourself to a different emotional standard than you hold other people?",
    "reflect_connect": "What story do you tell yourself privately that you would never say to someone you love?",
    "todays_practice": "When self-critical thoughts arise today, apply the same tools you have been using externally: pause, name the emotion, check the story, respond with care.",
    "micro_win_1": "I caught my inner critic in action",
    "micro_win_2": "I applied the same compassion I would give someone I love",
    "micro_win_3": "I checked the private story for accuracy",
    "today_i_feel_1": "Kinder to myself",
    "today_i_feel_2": "More honest",
    "today_i_feel_3": "Heavy but not hiding from it",
    "today_i_feel_4": "Ashamed",
    "today_i_feel_5": "Lonely",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will face the test of real sustained pressure.",
    "why_this_matters": "How you treat yourself when no one is watching is the baseline for everything else. If the inner voice is harsh in private, it does not matter how calm you appear in public \u2014 the internal cost is real. Changing the private voice is not about being soft with yourself. It is about being accurate. Most of what the inner critic says would not survive a fact-check.",
    "deeper_prompts": "[\"If someone recorded your inner voice for a day and played it back, what would you hear? Would you let someone you love listen to it?\", \"Where did your inner critic learn its vocabulary \\u2014 whose words is it using?\", \"What is one thing the inner critic says that you know is not true but still feels true?\"]",
    "try_this": "The next time the inner critic speaks, write down exactly what it says \u2014 word for word. Then read it as if someone said it to your best friend. Notice the difference in how you respond to the same words when they are directed at someone else.",
    "example": "Inner critic says: \"You always mess this up. Everyone else has it together. What is wrong with you?\" If a friend told you someone said that to them, you would say: \"That is not true. You are being too hard on yourself.\" Apply that response to yourself. Same words. Same compassion."
  },
  {
    "day_number": "25",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "Under Real Pressure",
    "writing_style": "fragment",
    "teaching_text": "Anyone can feel regulated in calm moments.\n\nPressure reveals what is real.\n\nWhen you are tired, overloaded, stretched thin, and one more thing hits \u2014 what happens then?\n\nToday is not about being perfect under pressure.\n\nIt is about staying aware enough to use one tool before the moment runs you.",
    "todays_reminder": "Being tested is not a failure of the practice. It is the point of the practice.",
    "todays_note": "Whatever you write here is between you and this page.",
    "todays_note_position": "after",
    "reflect_notice": "When you are under genuine pressure, what happens to your emotional regulation? What is the first thing to go?",
    "reflect_look_closer": "What is the earliest warning sign that you are approaching your threshold?",
    "reflect_connect": "Which of your tools remain most accessible under the highest pressure, and which disappear first?",
    "todays_practice": "When you sense you have crossed your threshold today, name it: I am past my limit right now. Then use the simplest tool available before engaging.",
    "micro_win_1": "I named when I was approaching my threshold",
    "micro_win_2": "I used at least one tool in a high-pressure moment",
    "micro_win_3": "I treated the difficult moment as practice",
    "today_i_feel_1": "Tested",
    "today_i_feel_2": "Proud of trying",
    "today_i_feel_3": "Overwhelmed but not pretending",
    "today_i_feel_4": "Defeated",
    "today_i_feel_5": "Angry",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will address what happens when you slip.",
    "why_this_matters": "Pressure is not a special circumstance where the rules change. It is the circumstance the rules were built for. Every tool you practiced in calmer moments was preparation for this. Under pressure, you will not rise to the level of your aspirations \u2014 you will fall to the level of your most practiced response. That is why the daily repetition matters.",
    "deeper_prompts": "[\"What type of pressure activates you most \\u2014 time pressure, performance pressure, emotional pressure, or interpersonal pressure?\", \"Under pressure, what is the first tool to go \\u2014 the pause, the breath, the naming, or the choosing?\", \"When you have handled pressure well in the past, what was different about that moment?\"]",
    "try_this": "Think of a pressure situation coming up this week. Write down your default pattern under pressure and the response you want to choose instead. Then rehearse the chosen response \u2014 literally say it out loud or walk through it mentally.",
    "example": "A tight deadline hits and your inbox is full. Old pattern: panic, try to do everything at once, snap at anyone who interrupts. With tools: pause. Feel the overwhelm. Name it: I am past my limit. Choose one task. Do it. Then the next. The work does not change. Your state does."
  },
  {
    "day_number": "26",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "When You Slip",
    "writing_style": "fragment",
    "teaching_text": "You will slip.\n\nThat does not erase your progress.\n\nGrowth is not measured by never reacting again.\n\nIt is measured by:\nhow fast you recover\nhow honestly you repair\nhow little shame you carry afterward\n\nToday is about what happens after the mistake.",
    "todays_reminder": "Progress is not measured by whether you slip. It is measured by how you respond after you do.",
    "todays_note": "You do not need to answer every question. One honest sentence counts.",
    "todays_note_position": "after",
    "reflect_notice": "Think of the most recent time you reacted in a way you later regretted. What happened?",
    "reflect_look_closer": "What did you do after it \u2014 did you address it, avoid it, or spiral into shame?",
    "reflect_connect": "Do you tend to punish yourself after slipping? What does that actually cost you \u2014 and does it change anything?",
    "todays_practice": "Complete the loop on a recent slip: name what happened, acknowledge the impact, identify what you would do differently, then consciously release the rumination.",
    "micro_win_1": "I assessed a slip honestly",
    "micro_win_2": "I completed the loop instead of ruminating",
    "micro_win_3": "I spent less time in shame than I might have before",
    "today_i_feel_1": "More forgiving",
    "today_i_feel_2": "Honest",
    "today_i_feel_3": "Still disappointed but moving forward",
    "today_i_feel_4": "Ashamed",
    "today_i_feel_5": "Frustrated",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will look at what your new default is becoming.",
    "why_this_matters": "The replay after a mistake is the cruelest loop because it combines real regret with the illusion of productivity. It feels like you are processing what happened. You are not. After the first honest look, every additional replay is punishment \u2014 and punishment does not change behavior. It just makes you more afraid of making the next mistake.",
    "deeper_prompts": "[\"What is your replay usually doing \\u2014 processing, punishing, or protecting you from the next mistake?\", \"How long does your average replay run before you can let it go \\u2014 hours, days, or longer?\", \"What would it look like to learn from a mistake in five minutes instead of five days?\"]",
    "try_this": "For a recent mistake, use this closure sequence: (1) What happened \u2014 one sentence. (2) What I would do differently \u2014 one sentence. (3) What I learned \u2014 one sentence. (4) I am letting the replay go. Say it, write it, then move on. If the replay starts again, repeat step 4 only.",
    "example": "You said something thoughtless to a friend. The replay runs for two days. But the facts are: you said it, you know why, and you have already apologized. Everything after the first honest look is the loop pretending to help. The closure sequence takes three minutes. The replay took two days."
  },
  {
    "day_number": "27",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "Your New Default",
    "writing_style": "fragment",
    "teaching_text": "Change does not arrive all at once.\nIt accumulates in small choices made consistently over time \u2014 in pauses that gradually become more automatic, in stories that become more accurate, in needs that become easier to name.\nYou are not at the end of this process.\nBut you are different than you were on Day 1.\nToday you look honestly at what has shifted \u2014 not what you aspire to, but what is actually different about how you move through the world.",
    "todays_reminder": "Notice the new version of you today. Naming it makes it real.",
    "todays_note": "If a question feels too much today, skip it and come back.",
    "todays_note_position": "after",
    "reflect_notice": "What is genuinely different about how you respond to charged situations compared to Day 1?",
    "reflect_look_closer": "What is beginning to become your new first response when something hard happens?",
    "reflect_connect": "What part of your pattern is still running most automatically, and what would the next stage of this work focus on?",
    "todays_practice": "Pay attention to moments today when the new default shows up naturally. Name them: That was different. That was new.",
    "micro_win_1": "I caught my new default operating naturally",
    "micro_win_2": "I named a specific change",
    "micro_win_3": "I named real progress without overstating it",
    "today_i_feel_1": "Different than Day 1",
    "today_i_feel_2": "Proud",
    "today_i_feel_3": "Uncertain but trusting the work",
    "today_i_feel_4": "Impatient",
    "today_i_feel_5": "Doubtful",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will build a plan for sustaining this work beyond Day 30.",
    "why_this_matters": "Most people do not notice gradual change. They compare today to their ideal and feel like they have failed. But comparing today to Day 1 tells a different story. You have tools now. You can name things you could not name a month ago. The change is real \u2014 it is just quiet. Naming it makes it visible and harder to dismiss.",
    "deeper_prompts": "[\"What would the Day 1 version of you think about where you are now?\", \"Which tool has become most natural \\u2014 the one you reach for without thinking?\", \"Where is the gap between where you are and where you want to be \\u2014 and is that gap smaller than it was four weeks ago?\"]",
    "try_this": "Write two lists: \"What I could not do on Day 1\" and \"What I can do now.\" Be specific. Not aspirations \u2014 evidence. Things that actually happened this month that the old version of you would not have done.",
    "example": "Day 1: you did not know what a trigger was. Now: you can name your top three triggers, you know which body signal comes first, you have paused at least once when the old pattern wanted to run. That is not nothing. That is the foundation of everything that comes next."
  },
  {
    "day_number": "28",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "The Long Game",
    "writing_style": "prose",
    "teaching_text": "Emotional patterns that took years to form take years to fully transform. What changes in 30 days is not the pattern itself \u2014 it is your relationship to the pattern. You are no longer unconscious of it. You are no longer entirely at its mercy. Sustaining that shift requires something most people never plan for: a realistic strategy for what comes after the workbook closes. Not a sprint. A life.",
    "todays_reminder": "What you decide now, in this moment of clarity, is what holds when the pressure returns.",
    "todays_note": "Short answers are complete answers.",
    "todays_note_position": "after",
    "reflect_notice": "Which tools and practices from this month can you realistically sustain?",
    "reflect_look_closer": "When the old pattern resurfaces in three months \u2014 not if, but when \u2014 what will you do?",
    "reflect_connect": "What people, practices, or environments will help you continue this work? What tends to pull you away from it?",
    "todays_practice": "Write a one-paragraph commitment to yourself: one practice you will keep, one pattern you will keep watching, and one resource you will turn to when the work gets hard again.",
    "micro_win_1": "I wrote a realistic sustainability plan",
    "micro_win_2": "I named what will threaten this work and how I will respond",
    "micro_win_3": "I committed to at least one ongoing practice",
    "today_i_feel_1": "Prepared",
    "today_i_feel_2": "Grounded",
    "today_i_feel_3": "Nervous about what comes next",
    "today_i_feel_4": "Overwhelmed",
    "today_i_feel_5": "Uncertain",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow you will claim a new emotional identity based on what you have lived this month.",
    "why_this_matters": "The biggest risk after a workbook like this is not that the tools stop working. It is that life gets busy and you stop using them. The pattern does not need you to fail. It just needs you to forget. A realistic sustainability plan is not about perfection \u2014 it is about having one practice that survives your busiest, hardest week.",
    "deeper_prompts": "[\"What has threatened your progress before \\u2014 in this or any other self-improvement work? What pulled you back into old patterns?\", \"Who in your life would support you in continuing this work \\u2014 and would you be willing to tell them what you are working on?\", \"What is the simplest version of this practice that you could maintain on your absolute worst day?\"]",
    "try_this": "Write your sustainability plan in three sentences: (1) The one practice I will keep. (2) The one signal that tells me I am slipping. (3) What I will do when that signal appears.",
    "example": "Plan: (1) I will check in with my body once a day \u2014 morning or night. (2) If I go three days without noticing a single reaction, that is the signal \u2014 it means I am back on autopilot. (3) When that happens, I will reread Day 1 and do one prompt. That is enough to restart."
  },
  {
    "day_number": "29",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "Your Emotional Identity",
    "writing_style": "prose",
    "teaching_text": "Identity is the most powerful force in human behavior. People act in accordance with who they believe themselves to be \u2014 even when it costs them. Lasting change is not just about new behaviors. It is about updating the belief about who you are. Today you write an identity statement \u2014 not aspirational, but grounded in evidence from the past 28 days. You do not need to believe it fully yet. You need to keep acting from it until the belief catches up.",
    "todays_reminder": "The discomfort of claiming this is the old identity recognizing it is being replaced.",
    "todays_note": "There is no wrong answer here. Write what is true.",
    "todays_note_position": "after",
    "reflect_notice": "How did you used to describe yourself emotionally? Write the old label exactly as you have used it.",
    "reflect_look_closer": "What happened this month that the old label cannot explain? Name three specific moments.",
    "reflect_connect": "Write a new identity statement: either \"I am becoming someone who...\" or \"I am someone who...\" \u2014 whichever feels honest. Base it on evidence.",
    "todays_practice": "Read your new identity statement aloud to yourself. Notice what happens in your body. If resistance shows up, that is normal. Read it again.",
    "micro_win_1": "I wrote a new identity statement grounded in evidence",
    "micro_win_2": "I read it aloud and stayed with whatever arose",
    "micro_win_3": "I acted from that identity in at least one moment",
    "today_i_feel_1": "Changed",
    "today_i_feel_2": "Hopeful",
    "today_i_feel_3": "Not sure yet but willing",
    "today_i_feel_4": "Exposed",
    "today_i_feel_5": "Skeptical",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Tomorrow is your final day. You will define the life you are building from who you are becoming.",
    "why_this_matters": "Identity is the deepest level of change. You can learn tools and forget them. You can build habits and break them. But when you change who you believe you are \u2014 from \"I am an emotional person\" to \"I am someone who notices emotions and chooses how to respond\" \u2014 the tools become natural because they are part of who you are.",
    "deeper_prompts": "[\"What labels have you carried longest \\u2014 \\\"too sensitive,\\\" \\\"too intense,\\\" \\\"too emotional,\\\" \\\"too much\\\"? Who gave you those labels?\", \"What evidence from this month proves those labels incomplete?\", \"If you lived fully from your new identity statement for the next six months, what specific things would change in your relationships, your work, and your inner life?\"]",
    "try_this": "Write your identity statement on a card or a note in your phone. Read it every morning for the next week. Not to convince yourself \u2014 but to remind yourself. Identity does not change through belief. It changes through repeated action.",
    "example": "Old label: \"I am just an angry person.\" New identity: \"I am someone who feels things deeply and is learning to respond with more awareness.\" The old label closes doors. The new one opens them \u2014 and it is based on evidence from the last 28 days."
  },
  {
    "day_number": "30",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "day_title": "The Life You Are Building",
    "writing_style": "fragment",
    "teaching_text": "Thirty days ago, you began with a question.\nWhy do I keep doing this?\nToday you leave with something stronger than an answer.\nYou leave with awareness.\nYou leave with tools.\nYou leave with proof that change is possible.\nYou may still get triggered.\nYou may still slip.\nYou may still have hard days.\nBut now you know:\nyou can pause\nyou can understand yourself\nyou can return\nyou can choose again\nThat changes everything.\nThis workbook ends here.\nYour next chapter does not.",
    "todays_reminder": "This is not the end. This is how it starts.",
    "todays_note": "Whatever you write here is between you and this page.",
    "todays_note_position": "after",
    "reflect_notice": "What was life like \u2014 emotionally, relationally, internally \u2014 before you began this workbook?",
    "reflect_look_closer": "What is different now \u2014 specifically and genuinely \u2014 about how you move through your life?",
    "reflect_connect": "What do you want the next six months to look like? Name one relationship, one pattern, and one thing you want to stop doing.",
    "todays_practice": "There is no new tool today. Live the day fully as the person you are becoming. Write one sentence \u2014 the truest thing you know about yourself after 30 days of this work. Keep it. Return to it.",
    "micro_win_1": "I completed 30 days of honest self-examination",
    "micro_win_2": "I have real tools and a real plan",
    "micro_win_3": "I am proud of showing up",
    "today_i_feel_1": "Ready",
    "today_i_feel_2": "Grateful",
    "today_i_feel_3": "Imperfect and that is enough",
    "today_i_feel_4": "Uncertain",
    "today_i_feel_5": "Emotional",
    "today_i_feel_6": "Other: ________",
    "looking_ahead": "Return to Day 1. Not because you failed \u2014 but because patterns have layers, and the second pass will reach places the first one could not.",
    "why_this_matters": "This is not a graduation. It is a beginning. The 30 days gave you awareness, language, tools, and evidence that change is possible. What comes next is the long work of living from what you now know \u2014 in real time, in real relationships, under real pressure. The workbook ends. The practice does not.",
    "deeper_prompts": "[\"Write a letter to the version of you who will be struggling in three months. What does that person need to hear from the version of you who just finished 30 days of honest work?\", \"What is the single most important thing you learned about yourself \\u2014 not a tool, not a technique, but something about who you are?\", \"If you come back to Day 1 and do this workbook again in six months, what do you think will be different the second time?\"]",
    "try_this": "Write one sentence \u2014 the truest thing you know about yourself after 30 days. Put it somewhere you will see it. Not on a shelf. Somewhere you will actually look \u2014 your bathroom mirror, your phone wallpaper, the first page of your journal.",
    "example": "Truest sentence examples (yours will be different): \"I am not my reactions \u2014 I am the person who can notice them.\" \"The pattern is old, but I am not the same person who started it.\" \"I can hold both the difficulty and the progress at the same time.\""
  }
];

export const weeks = [
  {
    "week_review_header": "WEEK 1 REVIEW",
    "week_number": "1",
    "week_theme": "SEE IT",
    "what_this_week_was_about": "This week was not about changing your reactions. It was about learning to see them clearly \u2014 without judgment, without fixing.\n\nMost people try to change before they understand. You did something different. You watched. You traced reactions to triggers, triggers to body signals, body signals to buildup patterns, and buildup to the environments feeding them.\n\nThat is the foundational move. Everything else in this workbook is built on top of what you did this week.",
    "weekly_checkin_1": "I noticed at least one pattern repeating across the week",
    "weekly_checkin_2": "I observed without immediately judging what I saw",
    "weekly_checkin_3": "I am ready to go beneath the surface next week",
    "keep_going_closing_text": "You are building a skill most people never learn. Next week, you begin understanding what lives beneath the reaction.",
    "reflect_prompt_1_where": "Where did your reactions show up most this week \u2014 relationships, body, self-talk, or somewhere else?",
    "reflect_prompt_2_what": "Was there a situation, person, or type of conversation that showed up more than once?",
    "what_surprised_me": "What reaction felt stronger than the situation seemed to warrant? What did you notice about yourself that you had not consciously seen before this week?",
    "what_was_the_hardest": "The day or prompt I most wanted to skip was \u2014 and what that resistance might be telling me is:",
    "pattern_map_item_1": "Triggers",
    "pattern_map_item_2": "Body Signals",
    "pattern_map_item_3": "Environment",
    "pattern_map_item_4": "Buildup",
    "pattern_map_item_5": "Observing Without Judgment",
    "pattern_map_scale_note": "1-5 scale (low to high)",
    "the_one_thing_prompt": "What is one reaction pattern you understand better now than you did 7 days ago?",
    "forward_section_label": "TAKING INTO NEXT WEEK",
    "forward_prompt": "Next week, you'll begin looking beneath reactions. What do you hope to understand more clearly about yourself?"
  },
  {
    "week_review_header": "WEEK 2 REVIEW",
    "week_number": "2",
    "week_theme": "FEEL IT",
    "what_this_week_was_about": "This week was not about managing your emotions. It was about meeting them honestly \u2014 perhaps for the first time in a long time. You went beneath the surface reaction to the real feeling underneath. You examined the stories your mind tells in difficult moments, the fears those stories protect, the origins that explain them, the needs those fears are hiding, and what happens when you push it all down. That is not light work. The fact that you kept going matters.",
    "weekly_checkin_1": "I identified the emotion beneath at least one reaction this week",
    "weekly_checkin_2": "I looked at a fear I usually avoid naming",
    "weekly_checkin_3": "I held something complex without forcing it to be simple",
    "keep_going_closing_text": "You cannot heal what you have not honestly felt. This week you felt it.",
    "reflect_prompt_1_where": "What feelings surfaced this week that you rarely acknowledge?",
    "reflect_prompt_2_what": "Where did you feel most resistant to looking closely \u2014 and what does that resistance tell you about what is still unexamined?",
    "what_surprised_me": "What surprised you about what lives beneath your most common reaction? Was the real emotion different from what you expected?",
    "what_was_the_hardest": "The prompt that brought up the most discomfort this week was \u2014 and I think the reason it was hard is:",
    "pattern_map_item_1": "The Emotion Beneath",
    "pattern_map_item_2": "The Story You Tell",
    "pattern_map_item_3": "Fear",
    "pattern_map_item_4": "Origins",
    "pattern_map_item_5": "Unmet Needs",
    "pattern_map_scale_note": "1-5 scale (low to high)",
    "the_one_thing_prompt": "What is the core fear or unmet need that seems to be driving your most common emotional pattern? Name it as plainly as you can.",
    "forward_section_label": "TAKING INTO NEXT WEEK",
    "forward_prompt": "Next week you begin shifting the pattern. What is one moment from this week where you wish you had responded differently \u2014 and what response would you choose now?"
  },
  {
    "week_review_header": "WEEK 3 REVIEW",
    "week_number": "3",
    "week_theme": "SHIFT IT",
    "what_this_week_was_about": "This week you stopped observing and started intervening. You built a three-second pause. You learned to use your breath as a reset, not just a reflex. You practiced naming what is real instead of becoming it. You made conscious choices in moments that used to run automatically. You rewrote an old story. You stated a limit. And you learned what to do when all of it falls apart. That is a week of genuine change \u2014 not aspiration, not intention. Actual practice in actual moments.",
    "weekly_checkin_1": "I used at least one tool in a real charged moment this week",
    "weekly_checkin_2": "I made at least one conscious choice instead of a default reaction",
    "weekly_checkin_3": "I treated a slip as data rather than evidence of failure",
    "keep_going_closing_text": "A person who can pause, name, and choose has a different life than one who cannot.",
    "reflect_prompt_1_where": "Which tools worked when you used them \u2014 the pause, the breath, the naming, or the choice?",
    "reflect_prompt_2_what": "Where did you notice the gap between stimulus and response beginning to widen?",
    "what_surprised_me": "Which tool surprised you most \u2014 either because it worked better than expected, or because it was harder to use than it looked?",
    "what_was_the_hardest": "The tool I found hardest to use in the actual moment \u2014 not in theory, but when something was happening \u2014 was:",
    "pattern_map_item_1": "The Pause",
    "pattern_map_item_2": "The Breath",
    "pattern_map_item_3": "Naming the Emotion",
    "pattern_map_item_4": "Choosing the Response",
    "pattern_map_item_5": "Setting Limits",
    "pattern_map_scale_note": "1-5 scale (low to high)",
    "the_one_thing_prompt": "Of all the tools you practiced this week, which one made the most concrete difference in a real situation? What made it work?",
    "forward_section_label": "TAKING INTO NEXT WEEK",
    "forward_prompt": "Next week you take everything into the hardest real-world contexts. Which relationship, environment, or situation are you most uncertain about bringing these tools into \u2014 and why?"
  },
  {
    "week_review_header": "WEEK 4 REVIEW",
    "week_number": "4",
    "week_theme": "LIVE IT",
    "what_this_week_was_about": "This week the work left the workbook and entered your life. You tested your tools in your closest relationship, under professional pressure, in the silence of being alone with your own thoughts, under real sustained stress, and in the aftermath of slipping. You looked at who you are becoming. You planned for the long game. You did not just read about change \u2014 you practiced it in the places that cost the most. That is what this week was for. That is what the whole month was for.",
    "weekly_checkin_1": "I brought at least one conscious tool into a real relationship or pressure situation",
    "weekly_checkin_2": "I caught my new default operating naturally \u2014 without reminding myself",
    "weekly_checkin_3": "I made a plan for sustaining this work beyond Day 30",
    "keep_going_closing_text": "The tools are only valuable when they become reflex. You are building that reflex now.",
    "reflect_prompt_1_where": "Where did your tools hold this week \u2014 and where did they give way?",
    "reflect_prompt_2_what": "Which context \u2014 relationships, work, pressure, solitude \u2014 revealed the most about how far you have come?",
    "what_surprised_me": "What genuinely surprised you about how you showed up this week \u2014 in a situation where the old pattern would have run unchallenged?",
    "what_was_the_hardest": "The moment I am most proud of from this entire month \u2014 not the biggest or most dramatic, but the one that felt most true \u2014 is:",
    "pattern_map_item_1": "Relationships",
    "pattern_map_item_2": "Work and Professional",
    "pattern_map_item_3": "Solitude and Self-Talk",
    "pattern_map_item_4": "Under Pressure",
    "pattern_map_item_5": "Recovery After Slipping",
    "pattern_map_scale_note": "1-5 scale (low to high)",
    "the_one_thing_prompt": "Looking across all four weeks, what is the one shift \u2014 in awareness, in emotion, in behavior, or in identity \u2014 that feels most permanent?",
    "forward_section_label": "CARRYING FORWARD",
    "forward_prompt": "What is the one practice, question, or insight from this month that you intend to carry forward \u2014 not as a resolution, but as a living part of how you move through your life?"
  }
];
